In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/diabetes.csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,0
4,0,137,40.0,35,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76.0,48,180.0,32.9,0.171,63,0
764,2,122,70.0,27,102.5,36.8,0.340,27,0
765,5,121,72.0,23,112.0,26.2,0.245,30,0
766,1,126,60.0,32,169.5,30.1,0.349,47,1
767,1,93,70.0,31,102.5,30.4,0.315,23,0

In [ ]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.495990
BloodPressure               0.174469
SkinThickness               0.295138
Insulin                     0.377081
BMI                         0.315577
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [ ]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [ ]:
X.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72.0,35,169.5,33.6,0.627,50
1,1,85,66.0,29,102.5,26.6,0.351,31
2,8,183,64.0,32,169.5,23.3,0.672,32
3,1,89,66.0,23,94.0,28.1,0.167,21
4,0,137,40.0,35,168.0,43.1,2.288,33

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

X=scaler.fit_transform(X)
X.shape

(768, 8)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Dropout

In [ ]:
model = Sequential()
model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(X_train,y_train,batch_size=32,epochs=100,validation_data=(X_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.4511 - loss: 0.7411 - val_accuracy: 0.6039 - val_loss: 0.6829
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6336 - loss: 0.6566 - val_accuracy: 0.6818 - val_loss: 0.6090
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6922 - loss: 0.5985 - val_accuracy: 0.7532 - val_loss: 0.5584
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7215 - loss: 0.5585 - val_accuracy: 0.7727 - val_loss: 0.5186
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7459 - loss: 0.5294 - val_accuracy: 0.8052 - val_loss: 0.4911
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7622 - loss: 0.5080 - val_accuracy: 0.8052 - val_loss: 0.4693
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4915 - val_accuracy: 0.8182 - val_loss: 0.4516
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7736 - loss: 0.4784 - val_accuracy: 0.8312 - val_loss: 0.4380
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7736 - loss: 0.4687 - val_accuracy: 0.8377 - val_loss: 0.4271
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7834 - loss: 0.4610 - val_accuracy: 0.8312 - val_loss: 0.4179
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7834 - loss: 0.4547 - val_accuracy: 0.8312 - val_loss: 0.4115
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7801 - loss: 0.4494 - val_accuracy: 0.8377 - val_loss: 0.4054
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4447 - val_accuracy: 0.8377 - val_loss: 0.3995
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7785 - loss: 0.4408 - val_accuracy: 0.8377 - val_loss: 0.3965
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7850 - loss: 0.4372 - val_accuracy: 0.8442 - val_loss: 0.3938
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7866 - loss: 0.4344 - val_accuracy: 0.8377 - val_loss: 0.3903
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7866 - loss: 0.4309 - val_accuracy: 0.8442 - val_loss: 0.3875
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7850 - loss: 0.4282 - val_accuracy: 0.8442 - val_loss: 0.3849
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7915 - loss: 0.4253 - val_accuracy: 0.8442 - val_loss: 0.3832
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4232 - val_accuracy: 0.8377 - val_loss: 0.3834
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4209 - val_accuracy: 0.8377 - val_loss: 0.3804
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4181 - val_accuracy: 0.8377 - val_loss: 0.3793
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4162 - val_accuracy: 0.8377 - val_loss: 0.3771
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4137 - val_accuracy: 0.8377 - val_loss: 0.3767
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4111 - val_accuracy: 0.8377 - val_loss: 0.3734
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4087 - val_accuracy: 0.8377 - val_loss: 0.3715
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4065 - val_accuracy: 0.8442 - val_loss: 0.3710
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4038 - val_accuracy: 0.8377 - val_loss: 0.3695
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4018 - val_accuracy: 0.8442 - val_loss: 0.3685
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.3995 - val_accuracy: 0.8442 - val_loss: 0.3670
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3975 - val_accuracy: 0.8377 - val_loss: 0.3665
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3952 - val_accuracy: 0.8377 - val_loss: 0.3646
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8094 - loss: 0.3929 - val_accuracy: 0.8442 - val_loss: 0.3619
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3909 - val_accuracy: 0.8442 - val_loss: 0.3589
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3884 - val_accuracy: 0.8506 - val_loss: 0.3579
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.3860 - val_accuracy: 0.8506 - val_loss: 0.3570
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3837 - val_accuracy: 0.8506 - val_loss: 0.3564
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3812 - val_accuracy: 0.8506 - val_loss: 0.3546
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3786 - val_accuracy: 0.8571 - val_loss: 0.3538
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8192 - loss: 0.3764 - val_accuracy: 0.8506 - val_loss: 0.3523
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3738 - val_accuracy: 0.8571 - val_loss: 0.3500
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3713 - val_accuracy: 0.8571 - val_loss: 0.3485
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3689 - val_accuracy: 0.8571 - val_loss: 0.3475
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3666 - val_accuracy: 0.8571 - val_loss: 0.3463
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3644 - val_accuracy: 0.8571 - val_loss: 0.3450
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3622 - val_accuracy: 0.8636 - val_loss: 0.3437
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8388 - loss: 0.3601 - val_accuracy: 0.8636 - val_loss: 0.3447
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3580 - val_accuracy: 0.8636 - val_loss: 0.3427
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3559 - val_accuracy: 0.8701 - val_loss: 0.3411
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3536 - val_accuracy: 0.8701 - val_loss: 0.3398
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3518 - val_accuracy: 0.8701 - val_loss: 0.3390
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8485 - loss: 0.3495 - val_accuracy: 0.8701 - val_loss: 0.3384
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8534 - loss: 0.3474 - val_accuracy: 0.8701 - val_loss: 0.3388
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8518 - loss: 0.3456 - val_accuracy: 0.8636 - val_loss: 0.3391
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3436 - val_accuracy: 0.8701 - val_loss: 0.3380
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3419 - val_accuracy: 0.8636 - val_loss: 0.3369
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3404 - val_accuracy: 0.8636 - val_loss: 0.3356
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3387 - val_accuracy: 0.8636 - val_loss: 0.3365
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3368 - val_accuracy: 0.8766 - val_loss: 0.3352
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8616 - loss: 0.3346 - val_accuracy: 0.8766 - val_loss: 0.3342
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8648 - loss: 0.3329 - val_accuracy: 0.8701 - val_loss: 0.3331
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8616 - loss: 0.3316 - val_accuracy: 0.8701 - val_loss: 0.3331
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8632 - loss: 0.3299 - val_accuracy: 0.8701 - val_loss: 0.3323
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8664 - loss: 0.3286 - val_accuracy: 0.8701 - val_loss: 0.3313
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.3272 - val_accuracy: 0.8766 - val_loss: 0.3315
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8730 - loss: 0.3259 - val_accuracy: 0.8766 - val_loss: 0.3293
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8697 - loss: 0.3246 - val_accuracy: 0.8766 - val_loss: 0.3300
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8697 - loss: 0.3230 - val_accuracy: 0.8701 - val_loss: 0.3292
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8730 - loss: 0.3223 - val_accuracy: 0.8766 - val_loss: 0.3283
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8730 - loss: 0.3208 - val_accuracy: 0.8766 - val_loss: 0.3288
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.3198 - val_accuracy: 0.8766 - val_loss: 0.3272
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.3191 - val_accuracy: 0.8701 - val_loss: 0.3278
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.3181 - val_accuracy: 0.8701 - val_loss: 0.3274
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8779 - loss: 0.3168 - val_accuracy: 0.8636 - val_loss: 0.3281
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8795 - loss: 0.3157 - val_accuracy: 0.8701 - val_loss: 0.3286
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8844 - loss: 0.3147 - val_accuracy: 0.8701 - val_loss: 0.3282
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8844 - loss: 0.3137 - val_accuracy: 0.8701 - val_loss: 0.3273
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8827 - loss: 0.3128 - val_accuracy: 0.8701 - val_loss: 0.3269
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8795 - loss: 0.3120 - val_accuracy: 0.8831 - val_loss: 0.3265
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8844 - loss: 0.3114 - val_accuracy: 0.8831 - val_loss: 0.3284
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8860 - loss: 0.3112 - val_accuracy: 0.8831 - val_loss: 0.3271
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8909 - loss: 0.3098 - val_accuracy: 0.8831 - val_loss: 0.3292
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8876 - loss: 0.3101 - val_accuracy: 0.8701 - val_loss: 0.3336
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8860 - loss: 0.3084 - val_accuracy: 0.8766 - val_loss: 0.3301
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8876 - loss: 0.3074 - val_accuracy: 0.8766 - val_loss: 0.3301
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8893 - loss: 0.3069 - val_accuracy: 0.8701 - val_loss: 0.3302
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8893 - loss: 0.3064 - val_accuracy: 0.8831 - val_loss: 0.3299
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8893 - loss: 0.3057 - val_accuracy: 0.8831 - val_loss: 0.3289
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8860 - loss: 0.3060 - val_accuracy: 0.8831 - val_loss: 0.3322
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8941 - loss: 0.3049 - val_accuracy: 0.8831 - val_loss: 0.3316
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8893 - loss: 0.3038 - val_accuracy: 0.8766 - val_loss: 0.3292
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8893 - loss: 0.3042 - val_accuracy: 0.8766 - val_loss: 0.3326
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8893 - loss: 0.3032 - val_accuracy: 0.8831 - val_loss: 0.3312
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8893 - loss: 0.3019 - val_accuracy: 0.8831 - val_loss: 0.3321
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8893 - loss: 0.3022 - val_accuracy: 0.8766 - val_loss: 0.3323
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8909 - loss: 0.3015 - val_accuracy: 0.8831 - val_loss: 0.3308
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8876 - loss: 0.3013 - val_accuracy: 0.8766 - val_loss: 0.3319
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8909 - loss: 0.3005 - val_accuracy: 0.8831 - val_loss: 0.3318
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8925 - loss: 0.2999 - val_accuracy: 0.8831 - val_loss: 0.3329
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8909 - loss: 0.2988 - val_accuracy: 0.8831 - val_loss: 0.3312

In [ ]:
pip install -U keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (26.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (1.83.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.13/dist-packages (from grpcio->keras-tuner) (4.16.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (2.1.3)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.20.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras->keras-tuner) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 3.2 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [ ]:
import keras_tuner as kt

In [ ]:

def build_model(hp):

  model=Sequential()

  counter=0

  for i in range(hp.Int('num_layer',min_value=1,max_value=10)):

    if counter==0:

      model.add(Dense(
          hp.Int('units'+str(i),min_value=8,max_value=128),
          activation=hp.Choice('activation' + str(i),values=['relu','sigmoid','tanh']),
          input_dim=8
          ))
      model.add(Dropout(hp.Choice('dropout' + str(i),values=[0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))

    else:
      model.add(Dense(
          hp.Int('units'+str(i),min_value=8,max_value=128),
          activation=hp.Choice('activation' + str(i),values=['relu','sigmoid','tanh'])
          ))
      model.add(Dropout(hp.Choice('dropout' + str(i),values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))

    counter+=1

  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer=hp.Choice('optimizer'+str(i),values=['adam','nadam','rmsprop','sgd']),
                loss='binary_crossentropy',
                metrics=['accuracy'])

  return model

In [ ]:
tuner=kt.RandomSearch(build_model,
                      objective='val_accuracy',
                      max_trials=5,
                      directory='mydir',
                      project_name='final2',
                      overwrite=True)

In [ ]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 5 Complete [00h 00m 06s]
val_accuracy: 0.6428571343421936

Best val_accuracy So Far: 0.798701286315918
Total elapsed time: 00h 00m 25s

In [ ]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'nadam', because it has 2 variables whereas the saved optimizer has 27 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
model.fit(X_train,y_train,epochs=100,initial_epoch=5,validation_data=(X_test,y_test))

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step - accuracy: 0.7182 - loss: 0.5412 - val_accuracy: 0.7987 - val_loss: 0.4619
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7117 - loss: 0.5460 - val_accuracy: 0.8052 - val_loss: 0.4379
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7606 - loss: 0.5055 - val_accuracy: 0.8117 - val_loss: 0.4266
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4862 - val_accuracy: 0.8247 - val_loss: 0.4161
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7492 - loss: 0.4895 - val_accuracy: 0.8247 - val_loss: 0.4127
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.4877 - val_accuracy: 0.8312 - val_loss: 0.4085
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7557 - loss: 0.4982 - val_accuracy: 0.8312 - val_loss: 0.4077
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4548 - val_accuracy: 0.8247 - val_loss: 0.4050
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4582 - val_accuracy: 0.8506 - val_loss: 0.4043
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4548 - val_accuracy: 0.7987 - val_loss: 0.4029
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4563 - val_accuracy: 0.7857 - val_loss: 0.4031
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7980 - loss: 0.4465 - val_accuracy: 0.8247 - val_loss: 0.3980
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7980 - loss: 0.4381 - val_accuracy: 0.8052 - val_loss: 0.3999
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7997 - loss: 0.4417 - val_accuracy: 0.7987 - val_loss: 0.4003
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8094 - loss: 0.4298 - val_accuracy: 0.8247 - val_loss: 0.3993
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8094 - loss: 0.4223 - val_accuracy: 0.8182 - val_loss: 0.3983
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8143 - loss: 0.4419 - val_accuracy: 0.8182 - val_loss: 0.4032
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8208 - loss: 0.4156 - val_accuracy: 0.8247 - val_loss: 0.4026
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8339 - loss: 0.3996 - val_accuracy: 0.8052 - val_loss: 0.4057
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8420 - loss: 0.4000 - val_accuracy: 0.8052 - val_loss: 0.4084
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8453 - loss: 0.4044 - val_accuracy: 0.8247 - val_loss: 0.4057
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8339 - loss: 0.4128 - val_accuracy: 0.8247 - val_loss: 0.4040
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8453 - loss: 0.4039 - val_accuracy: 0.8117 - val_loss: 0.4083
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8388 - loss: 0.3904 - val_accuracy: 0.8052 - val_loss: 0.4096
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8371 - loss: 0.4003 - val_accuracy: 0.8117 - val_loss: 0.4146
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8371 - loss: 0.3838 - val_accuracy: 0.8117 - val_loss: 0.4232
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8322 - loss: 0.3954 - val_accuracy: 0.8117 - val_loss: 0.4302
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8453 - loss: 0.3955 - val_accuracy: 0.8182 - val_loss: 0.4314
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8485 - loss: 0.4064 - val_accuracy: 0.8182 - val_loss: 0.4254
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8518 - loss: 0.3569 - val_accuracy: 0.8182 - val_loss: 0.4282
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8599 - loss: 0.3728 - val_accuracy: 0.8247 - val_loss: 0.4343
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8518 - loss: 0.3870 - val_accuracy: 0.8182 - val_loss: 0.4271
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8518 - loss: 0.3561 - val_accuracy: 0.8182 - val_loss: 0.4292
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8583 - loss: 0.3688 - val_accuracy: 0.8312 - val_loss: 0.4393
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8599 - loss: 0.3770 - val_accuracy: 0.8247 - val_loss: 0.4352
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8502 - loss: 0.3742 - val_accuracy: 0.8182 - val_loss: 0.4326
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8534 - loss: 0.3817 - val_accuracy: 0.8312 - val_loss: 0.4297
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8567 - loss: 0.3722 - val_accuracy: 0.8312 - val_loss: 0.4211
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8502 - loss: 0.3689 - val_accuracy: 0.8247 - val_loss: 0.4314
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8713 - loss: 0.3515 - val_accuracy: 0.8247 - val_loss: 0.4380
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8648 - loss: 0.3651 - val_accuracy: 0.8312 - val_loss: 0.4300
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8567 - loss: 0.3882 - val_accuracy: 0.8312 - val_loss: 0.4304
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8583 - loss: 0.3630 - val_accuracy: 0.8247 - val_loss: 0.4333
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8664 - loss: 0.3507 - val_accuracy: 0.8247 - val_loss: 0.4416
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8697 - loss: 0.3633 - val_accuracy: 0.8312 - val_loss: 0.4319
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8616 - loss: 0.3685 - val_accuracy: 0.8312 - val_loss: 0.4254
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8648 - loss: 0.3623 - val_accuracy: 0.8312 - val_loss: 0.4264
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8616 - loss: 0.3570 - val_accuracy: 0.8312 - val_loss: 0.4265
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8550 - loss: 0.3588 - val_accuracy: 0.8312 - val_loss: 0.4216
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8713 - loss: 0.3508 - val_accuracy: 0.8312 - val_loss: 0.4191
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8681 - loss: 0.3564 - val_accuracy: 0.8442 - val_loss: 0.4125
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8648 - loss: 0.3534 - val_accuracy: 0.8442 - val_loss: 0.4147
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.3627 - val_accuracy: 0.8442 - val_loss: 0.4156
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8811 - loss: 0.3360 - val_accuracy: 0.8442 - val_loss: 0.4189
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8730 - loss: 0.3460 - val_accuracy: 0.8506 - val_loss: 0.4157
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8746 - loss: 0.3509 - val_accuracy: 0.8506 - val_loss: 0.4075
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8762 - loss: 0.3416 - val_accuracy: 0.8506 - val_loss: 0.4040
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8746 - loss: 0.3317 - val_accuracy: 0.8506 - val_loss: 0.4079
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.3370 - val_accuracy: 0.8571 - val_loss: 0.4120
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8779 - loss: 0.3344 - val_accuracy: 0.8506 - val_loss: 0.4105
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8697 - loss: 0.3343 - val_accuracy: 0.8506 - val_loss: 0.4119
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8681 - loss: 0.3430 - val_accuracy: 0.8506 - val_loss: 0.4094
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8779 - loss: 0.3464 - val_accuracy: 0.8571 - val_loss: 0.4050
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8827 - loss: 0.3187 - val_accuracy: 0.8377 - val_loss: 0.4262
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8697 - loss: 0.3394 - val_accuracy: 0.8442 - val_loss: 0.4177
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8681 - loss: 0.3517 - val_accuracy: 0.8377 - val_loss: 0.4142
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8795 - loss: 0.3115 - val_accuracy: 0.8571 - val_loss: 0.4093
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8811 - loss: 0.3260 - val_accuracy: 0.8571 - val_loss: 0.4025
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8827 - loss: 0.3158 - val_accuracy: 0.8636 - val_loss: 0.4016
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8844 - loss: 0.3267 - val_accuracy: 0.8636 - val_loss: 0.4048
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8616 - loss: 0.3471 - val_accuracy: 0.8571 - val_loss: 0.4010
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8844 - loss: 0.3190 - val_accuracy: 0.8636 - val_loss: 0.3965
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8860 - loss: 0.3236 - val_accuracy: 0.8636 - val_loss: 0.3964
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8811 - loss: 0.3234 - val_accuracy: 0.8571 - val_loss: 0.3970
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8941 - loss: 0.3173 - val_accuracy: 0.8571 - val_loss: 0.4029
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8746 - loss: 0.3406 - val_accuracy: 0.8442 - val_loss: 0.4060
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8746 - loss: 0.3199 - val_accuracy: 0.8377 - val_loss: 0.4109
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8941 - loss: 0.3113 - val_accuracy: 0.8506 - val_loss: 0.4104
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9007 - loss: 0.3030 - val_accuracy: 0.8636 - val_loss: 0.4098
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8811 - loss: 0.3247 - val_accuracy: 0.8636 - val_loss: 0.3995
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8860 - loss: 0.3320 - val_accuracy: 0.8636 - val_loss: 0.3940
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8827 - loss: 0.3197 - val_accuracy: 0.8571 - val_loss: 0.3931
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8811 - loss: 0.3318 - val_accuracy: 0.8571 - val_loss: 0.3949
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8844 - loss: 0.3069 - val_accuracy: 0.8636 - val_loss: 0.4006
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8860 - loss: 0.3154 - val_accuracy: 0.8506 - val_loss: 0.4067
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8811 - loss: 0.3172 - val_accuracy: 0.8506 - val_loss: 0.4056
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8876 - loss: 0.3082 - val_accuracy: 0.8506 - val_loss: 0.4074
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8909 - loss: 0.3079 - val_accuracy: 0.8506 - val_loss: 0.4034
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8893 - loss: 0.3126 - val_accuracy: 0.8571 - val_loss: 0.3984
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8811 - loss: 0.3385 - val_accuracy: 0.8506 - val_loss: 0.3992
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8893 - loss: 0.3159 - val_accuracy: 0.8506 - val_loss: 0.3964
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8925 - loss: 0.3029 - val_accuracy: 0.8506 - val_loss: 0.4015
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8827 - loss: 0.3172 - val_accuracy: 0.8571 - val_loss: 0.4066
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8860 - loss: 0.3202 - val_accuracy: 0.8571 - val_loss: 0.4065
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8941 - loss: 0.3099 - val_accuracy: 0.8506 - val_loss: 0.4000